//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintMarketing.C28.ExchangeAgent.Agents.SprintMarketing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class TransportEmails : global::System.Configuration.ApplicationSettingsBase {
        
        private static TransportEmails defaultInstance = ((TransportEmails)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TransportEmails())));
        
        public static TransportEmails Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>eric@sprintmarketing.ca</string>
  <string>dominique@sprintmarketing.ca</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EmailAddresses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EmailAddresses"]));
            }
            set {
                this["EmailAddresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c28-connector.lan")]
        public string Connector {
            get {
                return ((string)(this["Connector"]));
            }
            set {
                this["Connector"] = value;
            }
        }
    }
}
